#!/bin/python3
import math
import os
import random
import re
import sys
import numpy as np
#
# Complete the 'simpleArraySum' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY ar as parameter.
#

matriz = [input('¿que matriz quieres sumar?')]
dimension_m = [int(len(matriz)),int(len(matriz[0]))]
def simpleArraySum(*ar):
    global resultado
    x = np.matrix(list(matriz))
    matriz.append
    print(matriz.insert(0,dimension_m))
    print(x.sum)



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
ar_count = int(input().strip())
ar = list(map(int, input().rstrip().split()))
result = simpleArraySum(ar)
fptr.write(str(result) + '\n')
fptr.close()

