#!/bin/python3
import math
import os
import random
import re
import sys
import numpy as np
#
# Complete the 'simpleArraySum' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY ar as parameter.
#

matriz = [input('¿que matriz quieres sumar?')]
dimension_m = [int(len(matriz)),int(len(matriz[1]))]
def simpleArraySum(ar):
    ar == np.matriz
    matriz.append
    resultado == matriz.sum
    print(matriz.append(0,dimension_m))
    print(resultado)





if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
ar_count = int(input().strip())
ar = list(map(int, input().rstrip().split()))
result = simpleArraySum(ar)
fptr.write(str(result) + '\n')
fptr.close()
